[package]
name = "scout"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
etcetera = "0.8.0"
ignore = "0.4.22"
itertools = "0.13.0"
ratatui = "0.27.0"
regex = "1.10.6"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
