[package]
name = "scout"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
# color-eyre = "0.6.3" # TODO: use
ratatui = "0.27.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
