[package]
name = "scout"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.18", features = ["derive"] }
etcetera = "0.8.0"
ignore = "0.4.22"
itertools = "0.13.0"
ratatui = "0.27.0"
regex = "1.10.6"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
tempfile = "3.12.0"

[lib]
name = "scout"
path = "src/lib.rs"
